-- Osh default script: drop generated web asset bundles.
-- A restored dump carries the asset attachments of the source database, whose
-- filestore files are usually missing locally, so the UI loads without CSS/JS.
-- Deleting them makes Odoo rebuild the bundles on the next page load.

-- The filter mirrors ir.attachment.regenerate_assets_bundles(): only public
-- bundles generated by the superuser for no particular view are removed, never
-- user-uploaded attachments. Odoo < 16 served bundles from /web/content/, so
-- both prefixes are covered.
DELETE FROM ir_attachment
 WHERE public = true
   AND res_model = 'ir.ui.view'
   AND res_id = 0
   AND create_uid = 1
   AND (url LIKE '/web/assets/%' OR url LIKE '/web/content/%');
