[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "repo-m"
version = "0.1.0"
requires-python = ">=3.10"

[project.entry-points."osh.plugins"]
repo-m = "repo_m"

[tool.setuptools]
package-dir = { "repo_m" = "." }
packages = ["repo_m"]

[tool.setuptools.package-data]
repo_m = ["pyproject.toml"]

[tool.osh]

[tool.osh.backends]
none = "None again."
