[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "osh-configx"
version = "0.1.0"
requires-python = ">=3.10"

[project.entry-points."osh.plugins"]
osh-configx = "osh_configx"

[tool.setuptools]
package-dir = { "osh_configx" = "." }
packages = ["osh_configx"]

[tool.setuptools.package-data]
osh_configx = ["pyproject.toml"]

[tool.osh]
extends = ["config"]
