[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "osh-rel"
version = "0.1.0"
requires-python = ">=3.10"

[project.entry-points."osh.plugins"]
osh-rel = "osh_rel"

[tool.setuptools]
package-dir = { "osh_rel" = "." }
packages = ["osh_rel"]

[tool.setuptools.package-data]
osh_rel = ["pyproject.toml"]

[tool.osh]
extends = ["db.list"]
