[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "osh-odoox"
version = "0.1.0"
requires-python = ">=3.10"

[project.entry-points."osh.plugins"]
osh-odoox = "osh_odoox"

[tool.setuptools]
package-dir = { "osh_odoox" = "." }
packages = ["osh_odoox"]

[tool.setuptools.package-data]
osh_odoox = ["pyproject.toml"]

[tool.osh]
extends = ["odoo"]
