[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "osh-bad"
version = "0.1.0"
requires-python = ">=3.10"

[project.entry-points."osh.plugins"]
osh-bad = "osh_bad"

[tool.setuptools]
package-dir = { "osh_bad" = "." }
packages = ["osh_bad"]

[tool.setuptools.package-data]
osh_bad = ["pyproject.toml"]

[tool.osh]

[tool.osh.commands]
bad = "A broken command."
