[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "repo-dep-cycle"
version = "0.1.0"
requires-python = ">=3.10"

[project.entry-points."osh.plugins"]
osh-cyc-a = "osh_cyc_a"
osh-cyc-b = "osh_cyc_b"

[tool.setuptools]
packages = ["osh_cyc_a", "osh_cyc_b"]

[tool.setuptools.package-data]
"*" = ["pyproject.toml"]
