[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "osh-odoosub"
version = "0.1.0"
requires-python = ">=3.10"

[project.entry-points."osh.plugins"]
osh-odoosub = "osh_odoosub"

[tool.setuptools]
package-dir = { "osh_odoosub" = "." }
packages = ["osh_odoosub"]

[tool.setuptools.package-data]
osh_odoosub = ["pyproject.toml"]

[tool.osh.group_commands.odoo]
sub = "Sub of odoo."
