[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "repo-meta-ok"
version = "0.1.0"
requires-python = ">=3.10"

[project.entry-points."osh.plugins"]
osh-extok = "osh_extok"
osh-prov = "osh_prov"

[tool.setuptools]
packages = ["osh_extok", "osh_prov"]

[tool.setuptools.package-data]
"*" = ["pyproject.toml"]
